# Generated by Django 4.0.2 on 2022-03-26 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('disease', models.CharField(max_length=200)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('scan', models.ImageField(upload_to='scans')),
                ('user', models.ForeignKey(default='tempo', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
